### ISSUE TITLE
Adding settings for update interval

### ISSUE THREAD

**Issue by mobilutz** [martijndierckx/homebridge-hydrawise#1]
I was amazed at how many connection my raspberry-pi is doing to hydrawise, which brought me to look for this:
https://github.com/martijndierckx/homebridge-hydrawise/blob/master/index.js#L90-L91

For me it would make sense to either increase this 5 seconds or make this part of the settings.

When I find time, I could open a PR. But this is an implementation another homebridge plugin uses:
https://github.com/henry-spanka/homebridge-buschjaeger/blob/master/index.js#L155-L165

**Comment by martijndierckx** [comment]
Don't have the time myself right now to do this, so if you can add the code for the parameterisation in a PR, it would be helpful.

**Comment by martijndierckx** [comment]
Done

**Comment by mobilutz** [comment]
Thanks for the implementation. 👍 
Now I will activate that homebridge plugin again ...
