### ISSUE TITLE
Idle and Updates

### ISSUE THREAD

**Issue by erpeters3** [martijndierckx/homebridge-hydrawise#12]
All latest plugins and homebridge.  Clicking button starts sprinklers, lights up, says “idle”.  But it works.  Button never updates.   Stays lit.   Stays saying idle.

**Comment by martijndierckx** [comment]
Can you post the debug output of homebridge ("homebridge -D") together with the output of the [troubleshooting script](https://github.com/martijndierckx/homebridge-hydrawise/blob/master/troubleshooting/hydrawise-api.js). Please make sure you remove your API key and passwords from the output before posting.

**Comment by erpeters3** [comment]
Apologies but I am unsure how to do either.  I use Homebridge-UI and I enabled debug mode in the console.  All I see are a bunch of device fetches.  I also have no clue what to do with the referenced script, not a developer, more of a dabbler :)

I will say since I applied the update that went out for Homebridge-Hydrawise yesterday, the on/off works fine, but the status never updates on the Home app button.  It lights up but always says "idle" and "waiting"

**Comment by fgomecs** [comment]
Here is a tip just in case you haven’t done it. 

Install the homebridge image to your raspberry, it comes with everything you need for the majority if the plugins to work out if the box. 

I have 7 zones, one controller and the latest build for Hydrawise and is working like a charm. I installed the plugin from the homebridge UI and it automatically asks for your API for Hydrawise and stuff. Works right out The box. 

Here is the link to the homebridge raps image: https://github.com/homebridge/homebridge-raspbian-image/blob/master/README.md

**Comment by erpeters3** [comment]
Did all of that, though I am running on a Mac with Homebridge-UI.  It now "works" as in the zone starts for 10 minutes.  But the button forever says "Idle" and the toggle switch if you long press the button says "waiting"


![FullSizeRender](https://user-images.githubusercontent.com/8429064/81623490-a6861e00-93c1-11ea-9124-a8cab80c5471.jpeg)

**Comment by erpeters3** [comment]
![IMG_0242](https://user-images.githubusercontent.com/8429064/81623522-bdc50b80-93c1-11ea-8b58-dc138a308360.png)

**Comment by fgomecs** [comment]
I’ve never ran homebridge in Macs just Pis

**Comment by martijndierckx** [comment]
Without debug info and the output of the troubleshooting scripts, there is not much I can do for you at the moment.

**Comment by erpeters3** [comment]
Did you see this comment above?   Apologies but I am unsure how to do either. I use Homebridge-UI and I enabled debug mode in the console. All I see are a bunch of device fetches. I also have no clue what to do with the referenced script, not a developer, more of a dabbler :)  So:

1-where is the log once i run as -D?
2-what Do I do with the script?

**Comment by jcbigears** [comment]
Apart from the homebridge -D output, could you explain how to run the troubleshooting script?
Thanks

**Comment by martijndierckx** [comment]
The details are at the top of the script:

```
If you run into issues, create an issue which contains the debug output of Homebridge ("homebridge -D") and the output of the following calls.
  PLEASE REMOVE YOUR API KEY/PASSWORD FROM THE OUTPUT BEFORE ADDING IT TO YOUR TICKET.
  
  Cloud connection:
  - Get Zones           -   node ./troubleshooting/hydrawise-api.js getZones YOUR_API_KEY
  - Get raw Schedule    -   node ./troubleshooting/hydrawise-api.js getSchedule YOUR_API_KEY
  Local connection:
  - Get Zones           -   node ./troubleshooting/hydrawise-api.js getZones IP_ADDRESS CONTROLLER_PASSWORD
  - Get raw Schedule    -   node ./troubleshooting/hydrawise-api.js getSchedule IP_ADDRESS CONTROLLER_PASSWORD
```

**Comment by jcbigears** [comment]
[homebridge D output.txt](https://github.com/martijndierckx/homebridge-hydrawise/files/4627238/homebridge.D.output.txt)
[troubleshooting.txt](https://github.com/martijndierckx/homebridge-hydrawise/files/4627239/troubleshooting.txt)

**Comment by jcbigears** [comment]
Thank you.
Please find outputs attached.
Regards,
John
[troubleshooting.txt](https://github.com/martijndierckx/homebridge-hydrawise/files/4627499/troubleshooting.txt)
[homebridge D output.txt](https://github.com/martijndierckx/homebridge-hydrawise/files/4627501/homebridge.D.output.txt)

**Comment by martijndierckx** [comment]
Hi I need a bit more info, I'm afraid.
Can you send me:
- the getZones & getSchedule troubleshooting output just before you start a sprinkler
- the getZones & getSchedule troubleshooting output just after you tried activating it, but before it actually turned on (only if you work via a CLOUD connection)
- the getZones & getSchedule troubleshooting output a couple of seconds after the sprinkler has turned on
- the 'homebridge -D' output from starting up until you completed the above.

thx
M

**Comment by jcbigears** [comment]
Thank you.
I think I've captured it as requested. Thanks so much for your time and efforts.
John
[output.txt](https://github.com/martijndierckx/homebridge-hydrawise/files/4634178/output.txt)

**Comment by jcbigears** [comment]
I just did a completely clean install of my Homebridge Pi and built up the config from scratch, but I'm still getting the same errors. Any ideas?

**Comment by martijndierckx** [comment]
I have not had the time to investigate in depth. But i’m guessing you’re running into the request limit of the cloud api.

Try to set the polling interval (in the advanced settings of config ui) to 15000. Reboot homebridge and let it run for 5mins before trying again.

**Comment by jcbigears** [comment]
Hello.
This was regarding the error about saying “idle” and “waiting” on the
switch.
No worries. No hurry at all!
John

On 22 May 2020, at 00:45, martijndierckx <notifications@github.com> wrote:

﻿

I have not had the time to investigate in depth. But i’m guessing you’re
running into the request limit of the cloud api.

Try to set the polling interval (in the advanced settings of config ui) to
15000. Reboot homebridge and let it run for 5mins before trying again.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/martijndierckx/homebridge-hydrawise/issues/12#issuecomment-632126664>,
or unsubscribe

**Comment by martijndierckx** [comment]
It seems something has changed at Hydrawise's side.
Can you do the following for me to confirm:

1. Start a zone via Homebridge
2. Stop homebridge to make sure you're not polling Hydrawise anymore so we're not running into rate limits (leave the zone running)
3. Wait 2 minutes
4. Run the following command:
  `curl "https://api.hydrawise.com/api/v1/statusschedule.php?api_key=YOUR_API_KEY"`

Send me the output of the command.
(You can of course start Homebridge again afterwards)

**Comment by jcbigears** [comment]
Hi.
As requested, output below.
I also noticed and installed your update - thank you.
As well, within Homebridge the valve icons appear correct and state "running" and "off" as appropriate. On my iphone and Home app on a mac, the icons also appear correct, except they state "idle" and "off", and the switch still reads "waiting" when it's turned on.
Thanks again,
John


> {"time":1590317544,"nextpoll":60,"message":"","simRelays":1,"options":1,"stupdate":0,"expanders":[],"sensors":[],"relays":[{"relay_id":1839402,"time":371256,"type":1,"run":1200,"relay":1,"name":"Front Gbeds","period":259200,"timestr":"Fri","stop":1},{"relay_id":1839422,"time":372456,"type":1,"run":360,"relay":2,"name":"Main lawn","period":259200,"timestr":"Fri","stop":1},{"relay_id":1839423,"time":372816,"type":1,"run":360,"relay":3,"name":"Small lawn","period":259200,"timestr":"Fri","stop":1},{"relay_id":1839403,"time":373176,"type":1,"run":1200,"relay":4,"name":"House Gbeds","period":259200,"timestr":"Fri","stop":1},{"relay_id":1839404,"time":1,"type":106,"run":1057,"relay":5,"name":"Pool Gbed","period":259200,"timestr":"Now","stop":1},{"relay_id":1839417,"time":1576800000,"type":110,"run":0,"relay":6,"name":"Pots","period"

**Comment by martijndierckx** [comment]
Is that the complete output?
It's seems like the last piece is missing...

**Comment by jcbigears** [comment]
I'll run it again and attach it here. The valve is "Front Gbeds".

In addition, several new errors were present in the log file that I hadn't seen before when I logged in. I've added the errors below as well.

[curl output.txt](https://github.com/martijndierckx/homebridge-hydrawise/files/4673421/curl.output.txt)
[errors.txt](https://github.com/martijndierckx/homebridge-hydrawise/files/4673422/errors.txt)

**Comment by martijndierckx** [comment]
This confirms my hunch that the Hydrawise API has changed.
I'll contact them to get an update...

**Comment by jcbigears** [comment]
> This confirms my hunch that the Hydrawise API has changed.
> I'll contact them to get an update...

Thank you!

**Comment by martijndierckx** [comment]
I've updated the library to correctly detect the status of the zone. Can you guys update and try again?

**Comment by erpeters3** [comment]
I could never get the logging or troubleshooter code to run properly.  I think it has something to do with the username under which homebridge is installed.  Thankfully others had similar issue and could get you the data you needed.  ALL FIXED here.  Thanks much for your efforts.   Works like a charm.
