### ISSUE TITLE
LOCAL settings

### ISSUE THREAD

**Issue by jcbigears** [martijndierckx/homebridge-hydrawise#13]
Hello and sorry if this is a newbie question. I'm running Homebridge, latest version, on a Pi and v1.0.4 of your hydrawise app. The Hydrawise unit is on the same network as the Pi, both with static IP addresses, so I'm trying to install it as a LOCAL. However, the Hunter Pro-HC unit required an email/password to be created, and so it's no longer admin/admin. I've pasted the config below, and attached the logs and Homebridge -D output.
[Homebridge -D output.txt](https://github.com/martijndierckx/homebridge-hydrawise/files/4625335/Homebridge.-D.output.txt)
[Log.txt](https://github.com/martijndierckx/homebridge-hydrawise/files/4625336/Log.txt)

Config:
            "name": "Hydrawise",
            "type": "LOCAL",
            "host": "192.168.86.219",
            "user": "john@email.com",
            "password": "PasswordX",
            "polling_interval": 100000,
            "platform": "HydrawisePlatform"
        }
    ]
}

**Comment by martijndierckx** [comment]
Another ticket is already open here:
https://github.com/paulmolluzzo/hydrawise-api/issues/7

**Comment by jcbigears** [comment]
Thank you. I’ll post there.

On 14 May 2020, at 17:46, martijndierckx <notifications@github.com> wrote:

﻿

Another ticket is already open here:
paulmolluzzo/hydrawise-api#7
<https://github.com/paulmolluzzo/hydrawise-api/issues/7>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/martijndierckx/homebridge-hydrawise/issues/13#issuecomment-628455935>,
or unsubscribe
