### ISSUE TITLE
The requested platform "HydrawisePlatform" was not registered by any plugin.

### ISSUE THREAD

**Issue by ghost** [martijndierckx/homebridge-hydrawise#14]
Hi there!

I'm getting the following message in my logs for the hydrawise plug-in. I'm running HOOBS on docker via a Synology. 
My config is setup for "CLOUD"

I followed the install method: 
Install homebridge using: npm install -g homebridge
Install this plugin using: npm install -g homebridge-hydrawise

AND I also tried installing from  the Plug-in "store" within HOOBS. 

`5/20/2020, 5:07:38 PM The requested platform "HydrawisePlatform" was not registered by any plugin.5/20/2020, 5:07:38 PM Your config.json is requesting the platform "HydrawisePlatform" which has not been published by any installed plugins.`

I appreciate any help and guidance on this! 

Thank you.

**Comment by BadgerBadgerAndFox** [comment]
I had a similar issue after updating my plugins, and homebridge (i'm using the official RPi image)
On restart it would throw that error and restart homebridge, this impacted multiple plugins (all was fine until i updated and only the updated plugins errored).
I use Config UI X to manage the plugins and config.
To resolve i had to remove the applicable plugin and config and then used Config UI X to install and repopulate via the GUI. This resolved my issue.

**Comment by ghost** [comment]
Thanks for your response @BadgerBadgerAndFox ! I ended up moving off of "HOOBS" and now run homebridge with Config UI X like you recommended. This did **resolve** the issue and I am able to see the sprinklers and control them. I am going to **assume** that my initial issue is tied to "HOOBS" specifically. 

However, I am experiencing the issue outlined in: #12 
This is a fresh install on docker. I have not attempted to replicate this on a raspberry pi...

**Comment by martijndierckx** [comment]
The platform name changed with the complete rewrite. So if anyone is running into this, make sure you are using the correct platform name.
