### ISSUE TITLE
Multiple controller 

### ISSUE THREAD

**Issue by montreuxxx** [martijndierckx/homebridge-hydrawise#17]
Hello Martin,
I tested the local setting for my two controllers. Regardless of whether I enter the IP address of one or the other controller  only the zones of one controller (same one) appear on the device list.
In the cloud it is the same controller.

Any ideas how to display the zones of the second controller?

All best, Mark

**Comment by martijndierckx** [comment]
Just to understand correctly...
You have 2 controllers, one with IP address X and one with IP address Y.
And it doesn't matter wether you configure controller X or Y in Homebridge via the local connection, you will always get to see the zones of controller X?

Via the cloud connection you get to see all zones of both controllers?

**Comment by montreuxxx** [comment]
Exact

**Comment by montreuxxx** [comment]
In both cases local and via cloud I see only one controller.
In local it doesn’t matter if I configure controller one with IP x or the second with IP Y. The result is I see always the same controller. The same I see in cloud mode.

**Comment by martijndierckx** [comment]
Can you send me the output of the following debug call for both controllers via the local connection?
It is true that the plugin/API-lib does not yet know how to handle multiple controllers via the cloud connection. (I have only one so I'm not able to test)

```
node ./troubleshooting/hydrawise-api.js getSchedule IP_ADDRESS CONTROLLER_PASSWORD
```

**Comment by montreuxxx** [comment]
I read in another ticket that local mode is no longer supported as of FW 3. I have FW 4.05.
Since I started with the cloud mode and the API key and only then switched to local mode, he still showed me zones, but these were only fictitious and do not work as I just found out.
Since the cloud mode does not support multicontrollers, this probably does not work with the version.
Too bad that there are not the possibilities to select the controller as in the app.
Or is it perhaps possible to integrate multiple cloud account instances? In that case, I would set up a cloud account for Hydrawise per controller

mark

**Comment by martijndierckx** [comment]
I'm working on the multi-controller implementation as we speak (first on hydrawise-api, and after that in the homebridge plugin).
I only have a single controller however, so it's hard for me to test. If anyone cares to (temporarily) share their API key, this would make it a lot easier.

**Comment by montreuxxx** [comment]
Hi 
yes I am ready to share mine. 
I don’t want to post it via this ticket. Please send me an email to montreuxxx at gmail dot com and I will send it to you.
Best mark

**Comment by martijndierckx** [comment]
I have updated the libraries to a new version which should work with multiple controllers.
Keep in mind that the available calls (30 per 5 minutes) need to be spread over your 2 controllers. So the more controllers you have, the longer it will take to get an update in homebridge.
