### ISSUE TITLE
run for duration

### ISSUE THREAD

**Issue by mshanemc** [martijndierckx/homebridge-hydrawise#20]
Awesome work...I'm posting two issue-ideas that I'm also willing to build.  Here's the first:

regarding
https://github.com/martijndierckx/homebridge-hydrawise/blob/c459a86e965bb82b7b4f39db629b32d13d491075/src/HydrawiseSprinkler.ts#L97

from what I can see, the API does let you run a zone with a duration.  
https://support.hydrawise.com/hc/en-us/article_attachments/360058265154/Hydrawise_REST_API.pdf

I'm thinking of 

- putting the default duration into the config file
- adding that to the run call

https://developers.homebridge.io/#/characteristic/SetDuration looks like the duration can be an input so I want to try that, too.

**Comment by martijndierckx** [comment]
Thanks for the compliment.

It is perfectly possible to start a zone for a given duration.
It is however not possible to query the default duration from Hydrawise, let alone change it.

What would be possible is to set a different default run time within the Homekit ecosystem, which does not sync with the default run time of hydrawise itself. Which would mean that if a zone was started from homekit it would run for X min, while if the same was done from hydrawise, it would run for Y min.

In any case ... the library on which this homebridge plugin was built, is already capable of running a zone for a given amount of time.

**Comment by martijndierckx** [comment]
Added in 1.2.0 (seems to work only on CLOUD)
