### ISSUE TITLE
followed direction but not working

### ISSUE THREAD

**Issue by eranhuman** [martijndierckx/homebridge-hydrawise#22]
Hey there,
New to Hoobs - very excited to see this plugin.
Followed directions and configured but not seeing anything show up in home.
Configured for cloud as thats where I know my crednetials work 100% and used API key.
Are there any known issues as of today?'
would really appreciate an assist.

**Comment by martijndierckx** [comment]
No known issues.
Please have a look at the troubleshooting script and post the output

**Comment by eranhuman** [comment]
happy to do that. am new to hoobs and am not super technical on the hoobs side of things so can you please tell me how to do that? :) Really appreciate.

**Comment by eranhuman** [comment]
to confirm once configured should just appear automatically in Home right?  Or is there a second step?

**Comment by eranhuman** [comment]
This is whats in the json file. is something missing?
   {
            "platform": "HydrawisePlatform",
            "plugin_map": {
                "plugin_name": "homebridge-hydrawise"
            },
            "name": "Hydrawise",
            "type": "CLOUD",
            "api_key": "MY KEY IS HERE",
            "polling_interval": 12000
        },

**Comment by eranhuman** [comment]
in what I think is the log 
7/13/2020, 2:40:40 PM [homebridge-zp.ZPS1] homebridge-zp v1.0.36, node 12.16.3, homebridge v3.2.6, homebridge-lib v4.7.117/13/2020, 2:40:40 PM [homebridge-zp.ZPS1] warning: 12.16.3: not using recommended node v12.18.1 LTS

**Comment by martijndierckx** [comment]
Can you try again?
@askovi pointed out an issue with the platform initialisation

**Comment by eranhuman** [comment]
We ARE GOOD!! thank YOU!!!!!
