### ISSUE TITLE
Cannot read property 'UUID' of undefined

### ISSUE THREAD

**Issue by savagee22** [martijndierckx/homebridge-hydrawise#3]
Hi,

I have issues with starting the homebridge. I have generated new API_KEY.

Thank you in advance for any help.

here is the log:

Jul 18 17:15:56 raspberrypi homebridge[1643]: [2018-7-18 17:15:56] [Hydrawise] TypeError: Cannot read property 'UUID' of undefined
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:139:35)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at /usr/local/lib/node_modules/homebridge-hydrawise/index.js:51:24
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at Array.map (<anonymous>)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at /usr/local/lib/node_modules/homebridge-hydrawise/index.js:38:17
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at tryCatcher (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/util.js:16:23)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/promise.js:512:31)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/promise.js:569:18)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/promise.js:614:10)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/promise.js:693:18)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at Async._drainQueue (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/async.js:133:16)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at Async._drainQueues (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/async.js:143:10)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/async.js:17:14)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at runCallback (timers.js:789:20)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at tryOnImmediate (timers.js:751:5)
Jul 18 17:15:56 raspberrypi homebridge[1643]:     at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by martijndierckx** [comment]
Can you add the following line of code to the currently empty line n° 37? After that, try and start homebridge and send me the output.

`console.log(data);`

**Comment by savagee22** [comment]
Here it is..

Jul 24 13:08:47 raspberrypi homebridge[8175]: { controller_id: 100899,
Jul 24 13:08:47 raspberrypi homebridge[8175]:   customer_id: 87782,
Jul 24 13:08:47 raspberrypi homebridge[8175]:   user_id: 93354,
Jul 24 13:08:47 raspberrypi homebridge[8175]:   nextpoll: 300,
Jul 24 13:08:47 raspberrypi homebridge[8175]:   sensors:
Jul 24 13:08:47 raspberrypi homebridge[8175]:    [ { input: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        type: 1,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        mode: 1,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        timer: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        offtimer: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        name: 'Rain sensor',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        offlevel: 1,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        active: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        relays: [Array] },
Jul 24 13:08:47 raspberrypi homebridge[8175]:      { input: 1,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        type: 3,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        mode: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        rate: 0.5,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        timer: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        offtimer: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        name: 'Vizora',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        flow: [Object],
Jul 24 13:08:47 raspberrypi homebridge[8175]:        relays: [Array] } ],
Jul 24 13:08:47 raspberrypi homebridge[8175]:   message: '',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   obs_rain: '1.6 mm',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   obs_rain_week: '20.9 mm',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   obs_maxtemp: '16.8 C',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   obs_rain_upgrade: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:   obs_rain_text: '24 Hours',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   obs_currenttemp: '',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   watering_time: '426  mins',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   water_saving: 22,
Jul 24 13:08:47 raspberrypi homebridge[8175]:   last_contact: '1 hour 45 minutes                 ago',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   forecast:
Jul 24 13:08:47 raspberrypi homebridge[8175]:    [ { temp_hi: '29 C',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        temp_lo: '16 C',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        conditions: 'Partly Cloudy'                ,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        day: 'Tuesday',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        pop: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        humidity: 51,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        wind: '18 km/h',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        icon: 'http://icons.wxug.co                m/i/c/k/partlycloudy.gif',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        icon_local: 'images/wug/par                tlycloudy.gif' },
Jul 24 13:08:47 raspberrypi homebridge[8175]:      { temp_hi: '30 C',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        temp_lo: '17 C',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        conditions: 'Clear',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        day: 'Wednesday',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        pop: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        humidity: 49,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        wind: '11 km/h',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        icon: 'http://icons.wxug.co                m/i/c/k/clear.gif',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        icon_local: 'images/wug/cle                ar.gif' },
Jul 24 13:08:47 raspberrypi homebridge[8175]:      { temp_hi: '30 C',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        temp_lo: '18 C',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        conditions: 'Clear',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        day: 'Thursday',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        pop: 0,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        humidity: 55,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        wind: '10 km/h',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        icon: 'http://icons.wxug.co                m/i/c/k/clear.gif',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        icon_local: 'images/wug/cle                ar.gif' },
Jul 24 13:08:47 raspberrypi homebridge[8175]:      { temp_hi: '30 C',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        temp_lo: '19 C',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        conditions: 'Partly Cloudy'                ,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        day: 'Friday',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        pop: 10,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        humidity: 58,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        wind: '8 km/h',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        icon: 'http://icons.wxug.co                m/i/c/k/partlycloudy.gif',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        icon_local: 'images/wug/par                tlycloudy.gif' } ],
Jul 24 13:08:47 raspberrypi homebridge[8175]:   status: 'All good!',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   status_icon: 'ok.png',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   name: 'Hydrawise',
Jul 24 13:08:47 raspberrypi homebridge[8175]:   relays:
Jul 24 13:08:47 raspberrypi homebridge[8175]:    [ { relay_id: 577951,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        relay: 1,
Jul 24 13:08:47 raspberrypi homebridge[8175]:        name: 'Bejarat',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        icon: 'grass.png',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        lastwater: '12 hours 8 minu                tes ago',
Jul 24 13:08:47 raspberrypi homebridge[8175]:        time: 42673,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        type: 1,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run: '11 minutes',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run_seconds: 660,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        nicetime: 'Wed, 25th Jul 3:                00am' },
Jul 24 13:08:48 raspberrypi homebridge[8175]:      { relay_id: 577975,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        relay: 2,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        name: 'Terasz',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        icon: 'grass.png',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        lastwater: '11 hours 55 min                utes ago',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        time: 43333,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        type: 1,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run: '14 minutes',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run_seconds: 840,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        nicetime: 'Wed, 25th Jul 3:                11am' },
Jul 24 13:08:48 raspberrypi homebridge[8175]:      { relay_id: 577984,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        relay: 3,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        name: 'Job hatso kert resz'                ,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        icon: 'barrow.png',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        lastwater: '11 hours 41 min                utes ago',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        time: 44173,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        type: 1,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run: '14 minutes',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run_seconds: 840,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        nicetime: 'Wed, 25th Jul 3:                25am' },
Jul 24 13:08:48 raspberrypi homebridge[8175]:      { relay_id: 578005,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        relay: 4,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        name: 'Hatso kozep kert res                z',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        icon: 'flower.png',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        lastwater: '11 hours 28 min                utes ago',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        time: 45013,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        type: 1,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run: '5 minutes',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run_seconds: 300,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        nicetime: 'Wed, 25th Jul 3:                39am' },
Jul 24 13:08:48 raspberrypi homebridge[8175]:      { relay_id: 579141,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        relay: 5,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        name: 'Bal hatso kert resz'                ,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        icon: 'leaf.png',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        lastwater: '11 hours 20 min                utes ago',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        time: 45313,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        type: 1,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run: '9 minutes',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run_seconds: 540,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        nicetime: 'Wed, 25th Jul 3:                44am' },
Jul 24 13:08:48 raspberrypi homebridge[8175]:      { relay_id: 579142,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        relay: 6,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        name: 'Csepegteto',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        icon: 'tree.png',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        lastwater: '1 day 12 hours                 ago',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        time: 127273,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        type: 1,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run: '32 minutes',
Jul 24 13:08:48 raspberrypi homebridge[8175]:        run_seconds: 1920,
Jul 24 13:08:48 raspberrypi homebridge[8175]:        nicetime: 'Thu, 26th Jul 2:                30am' } ] }
Jul 24 13:08:48 raspberrypi homebridge[8175]: [2018-7-24 13:08:47] [Hydrawise] T                ypeError: Cannot read property 'UUID' of undefined
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at Accessory.addService (/usr/                local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:139:3                5)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at /usr/local/lib/node_modules                /homebridge-hydrawise/index.js:51:24
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at Array.map (<anonymous>)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at /usr/local/lib/node_modules                /homebridge-hydrawise/index.js:38:17
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at tryCatcher (/usr/local/lib/                node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/util.js:16:23                )
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at Promise._settlePromiseFromH                andler (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/j                s/release/promise.js:512:31)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at Promise._settlePromise (/us                r/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/p                romise.js:569:18)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at Promise._settlePromise0 (/u                sr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/                promise.js:614:10)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at Promise._settlePromises (/u                sr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/                promise.js:693:18)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at Async._drainQueue (/usr/loc                al/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/async.                js:133:16)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at Async._drainQueues (/usr/lo                cal/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/release/async                .js:143:10)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at Immediate.Async.drainQueues                 (/usr/local/lib/node_modules/homebridge-hydrawise/node_modules/bluebird/js/rele                ase/async.js:17:14)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at runCallback (timers.js:789:                20)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at tryOnImmediate (timers.js:7                51:5)
Jul 24 13:08:48 raspberrypi homebridge[8175]:     at processImmediate [as _immed                iateCallback] (timers.js:722:5)

**Comment by martijndierckx** [comment]
I don't see anything unexpected in your API call results.

Can you make sure you're using the latest homebridge version?
The "Valve" type was only added in the later versions of HAP.
