### ISSUE TITLE
multiple controllers

### ISSUE THREAD

**Issue by montreuxxx** [martijndierckx/homebridge-hydrawise#5]
Hi Martin,
if I have multiple controllers, I get the zones only from the first one. How can I select a different controller?

All the best,
mark

**Comment by martijndierckx** [comment]
I only have a single controller, so I’m not able to test this.
But you’re very welcome to adapt the code to make this work for multiple controllers …

**Comment by montreuxxx** [comment]
... I do not know how and where to start :-)

**Comment by martijndierckx** [comment]
Hunter has published new versions of their API and new versions were published of this module and the hydrawise-api module. Can you retest?

**Comment by martijndierckx** [comment]
Not sure if the cloud version will handle multiple controllers well.
Creating multiple platform instances, one for each local controller will work.

Closing for now.
