### ISSUE TITLE
Supported Models?

### ISSUE THREAD

**Issue by mitch7391** [martijndierckx/homebridge-hydrawise#7]
Hi, I was wondering if this supports both the Pro-HC, Pro-C Hydrawise and other models?

**Comment by martijndierckx** [comment]
As long as it works on the hydrawise platform, it should.
________________________________
Van: mitch7391 <notifications@github.com>
Verzonden: Saturday, August 31, 2019 11:22:42 AM
Aan: martijndierckx/homebridge-hydrawise <homebridge-hydrawise@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [martijndierckx/homebridge-hydrawise] Supported Models? (#7)


Hi, I was wondering if this supports both the Pro-HC, Pro-C Hydrawise and other models?

**Comment by mitch7391** [comment]
Awesome :) thanks for the info
